kind: Secret
apiVersion: v1 
metadata:
  name: sample-secret
type: Opaque
data:
  username: bXktdXNlcm5hbWU=       # Base64 encoded value for "my-username"
  password: bXktcGFzc3dvcmQ=       # Base64 encoded value for "my-password"