kind: Service
apiVersion: v1
metadata:
  name: sample-nodeport
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  type: NodePort
  ports:
  - name: samplenodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 30007